# Site settings
title: Daniel Harris Enviro
email: dlz.harris@gmail.com
description: The Jekyll version of the Spectral theme by HTML5 UP.
baseurl: "" # the subpath of your site, e.g. /blog
url: https://dlzharris.github.io/ # the base hostname & protocol for your site
collections:
  - sections

# Homepage tiles
tiles-source: posts # accepts "posts" or "pages"
tiles-count: 3

# Misc settings
featured-image-source:

# Social settings
500px_url:
facebook_url:
github_url: https://github.com/dlzharris
gitlab_url: 
googleplus_url: 
instagram_url:
linkedin_url: https://www.linkedin.com/in/danielharrisenviro
pinterest_url:
slack_url:
twitter_url:

# Build settings
markdown: kramdown
